"""
Script 10: Per-FlowGAN-Fold Quality Metrics + Holdout (Reviewer Response)

Reviewer-driven companion to 01_quality_metrics.py and 02_regional_analysis.py.
It does NOT retrain FlowGAN. Instead, it reorganizes the existing per-subject
quality metrics by the FlowGAN training fold each subject belonged to.

The reviewer asked for:
  * mean +- SD across the 12 (we use 10 dev) folds, not pooled aggregates.
  * a clear deployment story (ensemble of 12 fold models vs. one retrain).
  * an unseen holdout reported separately.

FlowGAN was trained 12-fold; each subject's synthetic PET in df_pet_merged*.pkl
was generated by a model that did NOT see them. Per user decision:
  * folds 0..9 = development (10 folds, used for per-fold mean +- SD)
  * folds 10, 11 = holdout (~17%, reported separately)

This script does NOT load the FlowGAN model checkpoints (those are shared as
GitHub artifacts separately). It works entirely from the already-generated
synthetic PET volumes and the regional values in df_pet_merged*.pkl.

Outputs:
  tables/10_per_fold_quality_metrics/
    per_subject_quality_with_fold_{TLE,MCI}.csv   (cached; one row per subject)
    cv_summary_{TLE,MCI}.csv                       (per-metric mean+-SD across 10 dev folds)
    holdout_summary_{TLE,MCI}.csv                  (per-metric mean+-SD across holdout subjects)
    combined_summary_{TLE,MCI}.csv                 (side-by-side CV vs. holdout)

  figures/10_per_fold_quality_metrics/
    dev_vs_holdout_recon_{TLE,MCI}.{pdf,png}       (Real vs Synthetic, 4 panels)
    dev_vs_holdout_asl_{TLE,MCI}.{pdf,png}         (Real vs ASL baseline)
    per_fold_strip_{TLE,MCI}.{pdf,png}             (per-fold means as strips)
"""

import os
import sys
import json
import pickle
import argparse
import importlib.util
from typing import Dict, List

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from scipy import stats

from utils import save_figure, save_table, mean_and_95ci, get_quality_metrics


# ============================================================================
# Configuration
# ============================================================================

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
FIGURES_DIR = os.path.join(SCRIPT_DIR, 'figures', '10_per_fold_quality_metrics')
TABLES_DIR  = os.path.join(SCRIPT_DIR, 'tables',  '10_per_fold_quality_metrics')

DEV_FOLDS     = [f'fold_{i}' for i in range(10)]
HOLDOUT_FOLDS = ['fold_10', 'fold_11']

FOLD_JSON_TLE = os.path.join(SCRIPT_DIR, 'data', 'subjects_in_each_fold_TLE.json')
FOLD_JSON_MCI = os.path.join(SCRIPT_DIR, 'data', 'subjects_in_each_fold_MCI.json')

# Excluded regions for within-subject correlation (consistent with 02_ and 05_)
EXCLUDE_REGIONS = ['unknown', 'bankssts', 'Unknown', 'vessel', 'VentralDC',
                   'temporalpole', 'frontalpole', 'corpuscallosum', 'Putamen']

# Metrics that benefit from being LOWER (e.g., RMSE) — for plot orientation
HIGHER_BETTER = {'ssim', 'psnr', 'ncc', 'r'}
LOWER_BETTER  = {'rmse'}


# ============================================================================
# Load 01_quality_metrics.py via importlib (we reuse its NIfTI loaders &
# putamen normalization helper without touching it).
# ============================================================================

def _import_mod(name: str):
    path = os.path.join(SCRIPT_DIR, name)
    spec = importlib.util.spec_from_file_location(
        f'mod_{name.replace(".", "_").replace(" ", "_")}', path)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


MOD01 = _import_mod('01_quality_metrics.py')


# ============================================================================
# Fold mapping
# ============================================================================

def load_fold_map(json_path: str) -> Dict[str, str]:
    """Build {subject_id -> fold_name} from subjects_in_each_fold.json."""
    with open(json_path) as f:
        d = json.load(f)
    return {s: fold for fold, info in d.items() for s in info.get('test', [])}


# ============================================================================
# Per-subject volume-level quality metrics (cached on disk)
# ============================================================================

def _compute_volume_metrics_for_subject(sub: str, df_merged: pd.DataFrame,
                                       loaders: Dict[str, callable]) -> Dict:
    """Returns a metric dict or raises."""
    norm_og, norm_recon, norm_asl = MOD01.get_putamen_normalization(df_merged, sub)
    if not all([norm_og, norm_recon, norm_asl]):
        raise ValueError("missing/zero putamen normalization")

    pet_og = loaders['pet'](sub) / norm_og
    pet_rc = loaders['flowgan'](sub) / norm_recon
    asl    = loaders['asl'](sub) / norm_asl
    if asl.ndim == 4:
        asl = asl[:, :, :, 0]

    m_rc = get_quality_metrics(pet_og, pet_rc)
    m_as = get_quality_metrics(pet_og, asl)
    return {
        'ssim_recon': m_rc['ssim'], 'psnr_recon': m_rc['psnr'],
        'rmse_recon': m_rc['rmse'], 'ncc_recon':  m_rc['ncc'],
        'ssim_asl':   m_as['ssim'], 'psnr_asl':   m_as['psnr'],
        'rmse_asl':   m_as['rmse'], 'ncc_asl':    m_as['ncc'],
    }


def compute_volume_metrics(cohort: str, df_merged: pd.DataFrame,
                           force_recompute: bool) -> pd.DataFrame:
    cache = os.path.join(TABLES_DIR, f'per_subject_quality_{cohort}.csv')
    if not force_recompute and os.path.exists(cache):
        print(f"  Loading cached per-subject quality from {cache}")
        return pd.read_csv(cache)

    if cohort == 'TLE':
        loaders = {'pet': MOD01.load_pet_tle, 'flowgan': MOD01.load_flowgan_tle,
                   'asl': MOD01.load_asl_tle}
    elif cohort == 'MCI':
        loaders = {'pet': MOD01.load_pet_mci, 'flowgan': MOD01.load_flowgan_mci,
                   'asl': MOD01.load_asl_mci}
    else:
        raise ValueError(cohort)

    subjects = df_merged['subject'].unique()
    rows = []
    for sub in tqdm(subjects, desc=f"{cohort} volume-level quality"):
        try:
            metrics = _compute_volume_metrics_for_subject(sub, df_merged, loaders)
            rows.append({'subject': sub, **metrics})
        except Exception as e:
            print(f"  skip {sub}: {e}")

    df = pd.DataFrame(rows)
    os.makedirs(TABLES_DIR, exist_ok=True)
    df.to_csv(cache, index=False)
    print(f"  Cached {len(df)} subjects to {cache}")
    return df


# ============================================================================
# Per-subject within-subject Spearman correlation across regions
# ============================================================================

def compute_within_subject_corr(df_merged: pd.DataFrame, analysis_type: str
                                ) -> pd.DataFrame:
    """One row per subject with (r_recon, r_asl).
    analysis_type='SUVR'        : Spearman across regions of putamen-normalized values.
    analysis_type='Asymmetry'   : Spearman across regions of AI = (L-R)/(L+R).
    """
    rows = []
    subjects = df_merged['subject'].unique()
    for sub in subjects:
        df_s = df_merged[df_merged['subject'] == sub].copy()

        # Putamen normalization for this subject
        sub_mask = df_s['subject'] == sub
        l_og = df_s[sub_mask & (df_s['region_name'] == 'Putamen') & (df_s['side'] == 'Left')]['value_pet_original'].values
        r_og = df_s[sub_mask & (df_s['region_name'] == 'Putamen') & (df_s['side'] == 'Right')]['value_pet_original'].values
        l_rc = df_s[sub_mask & (df_s['region_name'] == 'Putamen') & (df_s['side'] == 'Left')]['value_pet_recon'].values
        r_rc = df_s[sub_mask & (df_s['region_name'] == 'Putamen') & (df_s['side'] == 'Right')]['value_pet_recon'].values
        l_as = df_s[sub_mask & (df_s['region_name'] == 'Putamen') & (df_s['side'] == 'Left')]['value_asl'].values
        r_as = df_s[sub_mask & (df_s['region_name'] == 'Putamen') & (df_s['side'] == 'Right')]['value_asl'].values
        if not all(len(x) > 0 for x in (l_og, r_og, l_rc, r_rc, l_as, r_as)):
            continue
        norm_og = float(l_og[0] + r_og[0])
        norm_rc = float(l_rc[0] + r_rc[0])
        norm_as = float(l_as[0] + r_as[0])
        if not all([norm_og, norm_rc, norm_as]):
            continue

        df_s['_og']  = df_s['value_pet_original'] / norm_og
        df_s['_rc']  = df_s['value_pet_recon']    / norm_rc
        df_s['_asl'] = df_s['value_asl']          / norm_as

        if analysis_type == 'SUVR':
            d = df_s.dropna(subset=['_og', '_rc', '_asl'])
            d = d[~d['region_name'].isin(EXCLUDE_REGIONS)]
            if len(d) < 5:
                continue
            r_rc_val, _  = stats.spearmanr(d['_og'], d['_rc'])
            r_asl_val, _ = stats.spearmanr(d['_og'], d['_asl'])
        else:  # Asymmetry
            left  = df_s[df_s['side'] == 'Left'].set_index('region_name')
            right = df_s[df_s['side'] == 'Right'].set_index('region_name')
            common = [r for r in left.index
                      if r in right.index and r not in EXCLUDE_REGIONS]
            if len(common) < 5:
                continue
            left  = left.loc[common]
            right = right.loc[common]
            ai_og = ((left['_og']  - right['_og'])  /
                     (left['_og']  + right['_og'])).values
            ai_rc = ((left['_rc']  - right['_rc'])  /
                     (left['_rc']  + right['_rc'])).values
            ai_as = ((left['_asl'] - right['_asl']) /
                     (left['_asl'] + right['_asl'])).values
            valid = np.isfinite(ai_og) & np.isfinite(ai_rc) & np.isfinite(ai_as)
            if valid.sum() < 5:
                continue
            r_rc_val,  _ = stats.spearmanr(ai_og[valid], ai_rc[valid])
            r_asl_val, _ = stats.spearmanr(ai_og[valid], ai_as[valid])

        rows.append({'subject': sub,
                     'r_recon': float(r_rc_val) if r_rc_val == r_rc_val else np.nan,
                     'r_asl':   float(r_asl_val) if r_asl_val == r_asl_val else np.nan})
    return pd.DataFrame(rows)


# ============================================================================
# Per-fold aggregation
# ============================================================================

METRIC_COLS = ['ssim_recon', 'ssim_asl',
               'psnr_recon', 'psnr_asl',
               'rmse_recon', 'rmse_asl',
               'ncc_recon',  'ncc_asl',
               'r_recon',    'r_asl']


def attach_fold(df_subject: pd.DataFrame, fold_map: Dict[str, str]) -> pd.DataFrame:
    df = df_subject.copy()
    df['fold'] = df['subject'].map(fold_map)
    df['split'] = df['fold'].apply(
        lambda f: 'holdout' if f in HOLDOUT_FOLDS
                  else ('dev' if f in DEV_FOLDS else 'unknown'))
    return df


def _safe_mean_ci(values: np.ndarray) -> tuple:
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if len(values) == 0:
        return np.nan, np.nan, np.nan, np.nan
    m = float(np.mean(values))
    if len(values) < 2:
        return m, 0.0, m, m
    sd = float(np.std(values, ddof=1))
    if sd == 0.0:
        return m, 0.0, m, m
    _, lo, hi = mean_and_95ci(values)
    return m, sd, float(lo), float(hi)


def summarize_dev_folds(df_subject: pd.DataFrame) -> pd.DataFrame:
    """For each metric: compute one mean per dev fold (10 fold-means),
    then aggregate (mean +/- SD +/- 95% CI) across the fold-means.
    This is what the reviewer asked for."""
    rows = []
    dev = df_subject[df_subject['split'] == 'dev']
    for metric in METRIC_COLS:
        fold_means = (dev.groupby('fold')[metric]
                         .mean()
                         .reindex(DEV_FOLDS)  # ensures all 10 dev folds appear
                         .values)
        m, sd, lo, hi = _safe_mean_ci(fold_means)
        rows.append({
            'metric':       metric,
            'n_folds_used': int(np.isfinite(fold_means).sum()),
            'fold_mean':    m,
            'fold_sd':      sd,
            'fold_ci_low':  lo,
            'fold_ci_high': hi,
            'fold_means':   ';'.join('NA' if not np.isfinite(v) else f'{v:.4f}'
                                     for v in fold_means),
        })
    return pd.DataFrame(rows)


def summarize_holdout(df_subject: pd.DataFrame) -> pd.DataFrame:
    """Direct per-subject summary over the 2 holdout folds (treated as one set)."""
    rows = []
    ho = df_subject[df_subject['split'] == 'holdout']
    for metric in METRIC_COLS:
        m, sd, lo, hi = _safe_mean_ci(ho[metric].values)
        rows.append({
            'metric':            metric,
            'n_holdout_subjects': int(np.isfinite(ho[metric].values).sum()),
            'holdout_mean':       m,
            'holdout_sd':         sd,
            'holdout_ci_low':     lo,
            'holdout_ci_high':    hi,
        })
    return pd.DataFrame(rows)


# ============================================================================
# Figures
# ============================================================================

def plot_dev_vs_holdout(df_subject: pd.DataFrame, panel_metrics: List[str],
                        title: str) -> plt.Figure:
    """For each panel metric, show dev fold-means (10 points) vs. holdout
    subject values (n_holdout points) as a strip + box."""
    fig, axes = plt.subplots(1, len(panel_metrics),
                             figsize=(4.5 * len(panel_metrics), 5))
    if len(panel_metrics) == 1:
        axes = [axes]

    for ax, metric in zip(axes, panel_metrics):
        dev_fold_means = (df_subject[df_subject['split'] == 'dev']
                          .groupby('fold')[metric].mean()
                          .reindex(DEV_FOLDS).values)
        ho_vals = df_subject[df_subject['split'] == 'holdout'][metric].dropna().values

        long_rows = []
        for v in dev_fold_means:
            if np.isfinite(v):
                long_rows.append({'value': v, 'split': 'CV fold means (n=10)'})
        for v in ho_vals:
            long_rows.append({'value': v,
                              'split': f'Holdout subjects (n={len(ho_vals)})'})
        d = pd.DataFrame(long_rows)
        if d.empty:
            ax.set_visible(False)
            continue
        order = sorted(d['split'].unique())
        sns.boxplot(data=d, x='split', y='value', ax=ax,
                    order=order, width=0.5, palette=['#66c2a5', '#fc8d62'],
                    showfliers=False, linewidth=2)
        sns.stripplot(data=d, x='split', y='value', ax=ax, order=order,
                      color='black', size=5, alpha=0.7, jitter=0.15)
        ax.set_title(metric, fontweight='bold')
        ax.set_xlabel('')
        ax.set_ylabel(metric)
        sns.despine(ax=ax)
        # Rotate labels for readability
        ax.set_xticklabels(ax.get_xticklabels(), rotation=15, ha='right')

    fig.suptitle(title, fontweight='bold', y=1.02)
    plt.tight_layout()
    return fig


def plot_per_fold_strip(df_subject: pd.DataFrame, title: str) -> plt.Figure:
    """For the headline metric pair (within-subject Spearman r and SSIM),
    plot per-fold mean as a strip across the 10 dev folds with holdout band."""
    pairs = [
        ('r_recon',    'r_asl',    'Within-subject Spearman r'),
        ('ssim_recon', 'ssim_asl', 'SSIM'),
    ]
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    for ax, (col_rc, col_as, panel_title) in zip(axes, pairs):
        dev = df_subject[df_subject['split'] == 'dev']
        ho  = df_subject[df_subject['split'] == 'holdout']

        fold_means_rc = (dev.groupby('fold')[col_rc].mean()
                            .reindex(DEV_FOLDS).values)
        fold_means_as = (dev.groupby('fold')[col_as].mean()
                            .reindex(DEV_FOLDS).values)

        x = np.arange(len(DEV_FOLDS))
        ax.scatter(x - 0.15, fold_means_rc, color='#1f77b4', s=70, alpha=0.85,
                   edgecolor='black', label='Synthetic (per-fold means)')
        ax.scatter(x + 0.15, fold_means_as, color='#ff7f0e', s=70, alpha=0.85,
                   edgecolor='black', label='ASL (per-fold means)')

        # Holdout reference: mean +/- SD as horizontal bands
        for vals, color, lbl in [
                (ho[col_rc].values, '#1f77b4', 'Synthetic holdout'),
                (ho[col_as].values, '#ff7f0e', 'ASL holdout')]:
            vals = vals[np.isfinite(vals)]
            if len(vals) == 0:
                continue
            m = vals.mean()
            sd = vals.std(ddof=1) if len(vals) > 1 else 0.0
            ax.axhline(m, color=color, linestyle='--', alpha=0.7, lw=2,
                       label=f'{lbl} mean={m:.2f}')
            ax.axhspan(m - sd, m + sd, color=color, alpha=0.10)

        ax.set_xticks(x)
        ax.set_xticklabels([f.replace('fold_', '') for f in DEV_FOLDS])
        ax.set_xlabel('Dev fold')
        ax.set_ylabel(panel_title, fontweight='bold')
        ax.set_title(panel_title, fontweight='bold')
        ax.legend(loc='best', fontsize=8)
        sns.despine(ax=ax)

    fig.suptitle(title, fontweight='bold', y=1.02)
    plt.tight_layout()
    return fig


# ============================================================================
# Cohort orchestration
# ============================================================================

def run_cohort(cohort: str, df_merged: pd.DataFrame, fold_map: Dict[str, str],
               force_recompute: bool):
    print(f"\n{'='*70}\n{cohort} - per-FlowGAN-fold quality metrics\n{'='*70}")

    # 1) Volume-level metrics (loads NIfTIs; cached on disk)
    df_q = compute_volume_metrics(cohort, df_merged, force_recompute)

    # 2) Within-subject Spearman correlation (cheap; recomputed each run)
    analysis_type = 'Asymmetry' if cohort == 'TLE' else 'SUVR'
    df_w = compute_within_subject_corr(df_merged, analysis_type)

    # 3) Merge per-subject metrics + fold tag
    df_subj = df_q.merge(df_w, on='subject', how='outer')
    df_subj = attach_fold(df_subj, fold_map)

    n_dev      = (df_subj['split'] == 'dev').sum()
    n_holdout  = (df_subj['split'] == 'holdout').sum()
    n_unknown  = (df_subj['split'] == 'unknown').sum()
    print(f"  Subjects: dev={n_dev}, holdout={n_holdout}, unknown_fold={n_unknown}")
    if n_unknown:
        unk = df_subj[df_subj['split'] == 'unknown']['subject'].tolist()
        print(f"    (unknown fold: {unk[:5]}{'...' if len(unk) > 5 else ''})")

    save_table(df_subj, f'per_subject_quality_with_fold_{cohort}', TABLES_DIR)

    # 4) Per-fold summary
    dev_sum = summarize_dev_folds(df_subj)
    ho_sum  = summarize_holdout(df_subj)
    save_table(dev_sum, f'cv_summary_{cohort}', TABLES_DIR)
    save_table(ho_sum,  f'holdout_summary_{cohort}', TABLES_DIR)

    # Print headline numbers
    print(f"\n  CV (10 dev folds): per-metric mean +/- SD over fold-means")
    for _, row in dev_sum.iterrows():
        print(f"    {row['metric']:<12} {row['fold_mean']:+.3f} +/- {row['fold_sd']:.3f}  "
              f"(95% CI [{row['fold_ci_low']:+.3f}, {row['fold_ci_high']:+.3f}])")
    print(f"\n  Holdout ({n_holdout} subjects): direct per-subject mean +/- SD")
    for _, row in ho_sum.iterrows():
        print(f"    {row['metric']:<12} {row['holdout_mean']:+.3f} +/- {row['holdout_sd']:.3f}  "
              f"(95% CI [{row['holdout_ci_low']:+.3f}, {row['holdout_ci_high']:+.3f}])")

    # 5) Combined side-by-side table for the manuscript
    combined = dev_sum.merge(ho_sum, on='metric', how='outer')
    save_table(combined, f'combined_summary_{cohort}', TABLES_DIR)

    # 6) Figures
    fig = plot_dev_vs_holdout(df_subj,
                              ['ssim_recon', 'psnr_recon', 'ncc_recon', 'r_recon'],
                              f'{cohort}: Real vs Synthetic FlowGAN')
    save_figure(fig, f'dev_vs_holdout_recon_{cohort}', FIGURES_DIR)
    plt.close(fig)

    fig = plot_dev_vs_holdout(df_subj,
                              ['ssim_asl', 'psnr_asl', 'ncc_asl', 'r_asl'],
                              f'{cohort}: Real vs ASL (baseline)')
    save_figure(fig, f'dev_vs_holdout_asl_{cohort}', FIGURES_DIR)
    plt.close(fig)

    fig = plot_per_fold_strip(df_subj, f'{cohort}: per-fold means with holdout reference')
    save_figure(fig, f'per_fold_strip_{cohort}', FIGURES_DIR)
    plt.close(fig)

    return df_subj


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description='Per-FlowGAN-fold quality metrics + holdout (reviewer response).')
    parser.add_argument('--force', action='store_true',
                        help='Recompute per-subject volume-level metrics from NIfTIs '
                             '(otherwise loads the cached per_subject_quality_*.csv).')
    parser.add_argument('--tle-only', action='store_true', help='Run only TLE.')
    parser.add_argument('--mci-only', action='store_true', help='Run only MCI.')
    args = parser.parse_args()

    os.makedirs(FIGURES_DIR, exist_ok=True)
    os.makedirs(TABLES_DIR,  exist_ok=True)

    if not args.mci_only:
        with open(os.path.join(SCRIPT_DIR, 'df_pet_merged.pkl'), 'rb') as f:
            df_tle = pickle.load(f)
        fold_map_tle = load_fold_map(FOLD_JSON_TLE)
        run_cohort('TLE', df_tle, fold_map_tle, args.force)

    if not args.tle_only:
        with open(os.path.join(SCRIPT_DIR, 'df_pet_merged_mci.pkl'), 'rb') as f:
            df_mci = pickle.load(f)
        fold_map_mci = load_fold_map(FOLD_JSON_MCI)
        run_cohort('MCI', df_mci, fold_map_mci, args.force)

    print("\n" + "=" * 70)
    print("Done.")
    print(f"Figures: {FIGURES_DIR}")
    print(f"Tables:  {TABLES_DIR}")
    print("=" * 70)


if __name__ == '__main__':
    main()
